// import { Inter } from "next/font/google";
import { Zen_Dots } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import { Toaster } from "react-hot-toast";
import Footer from "./components/body/Footer";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
// const zenDots = Zen_Dots({ weight: "400", subsets: ["latin"] });
// const poppins = Poppins({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Certificate Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex text-zinc-900 justify-center">
        <Toaster
          toastOptions={{ duration: 6000 }}
          position="top-right"
          reverseOrder={false}
        />
        <Analytics />
        <SpeedInsights />
        <div className="container px-2  lg:px-20 xl:px-40 2xl:px-80 py-2 lg:py-8 relative flex flex-col gap-4">
          <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:14px_14px] [mask-image:radial-gradient(ellipse_80%_50%_at_50%_0%,#000_70%,transparent_110%)]"></div>
          <Header />
          <div className=" min-h-80">{children}</div>
          <div className="flex justify-center">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
